packages:
    - "apps/*"
    - "contracts/*"
    - "contracts/jwt-guards/*"
    - "docs"
    - "packages/auth"
    - "packages/backend/*"
    - "packages/sdks/*"
    - "packages/providers/*"
    - "packages/shared/*"
    - "examples/custom-backend"
    - "examples/spa"
    - "examples/mobile"
