packages:
    - "contracts/auth0-guard"
    - "contracts/fa"
    - "contracts/jwt-guard-router"
    - "docs"
    - "packages/auth"
    - "packages/sdks/*"
    - "packages/shared/*"
    - "examples/custom-backend"
    - "examples/spa"
