export enum FirebaseProviderErrorCodes {
    USER_NOT_LOGGED_IN = "USER_NOT_LOGGED_IN",
    FIREBASE_NOT_INITIALIZED = "FIREBASE_NOT_INITIALIZED",
    INVALID_PROVIDER = "INVALID_PROVIDER",
    REQUEST_TRANSACTION_SIGNATURE_FAILED = "REQUEST_TRANSACTION_SIGNATURE_FAILED",
    REQUEST_DELEGATE_TRANSACTION_SIGNATURE_FAILED = "REQUEST_DELEGATE_TRANSACTION_SIGNATURE_FAILED",
    SIGNATURE_REQUEST_NOT_FOUND = "SIGNATURE_REQUEST_NOT_FOUND",
}

export class FirebaseProviderError extends Error {
    constructor(code: FirebaseProviderErrorCodes) {
        super(code.toString());
        this.name = "FirebaseProviderError";
    }
}
