[package]
name = "jwt-implementation"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
near-sdk = "5.9"

[dev-dependencies]
near-sdk = { version = "5.9", features = ["unit-testing"] } 