name: "Build base image"

on:
  workflow_call:
    inputs:
      push:
        required: true
        type: boolean
      tag:
        required: true
        type: string

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      # Checkout repository under $GITHUB_WORKSPACE path
      - name: Repository checkout
        uses: actions/checkout@v4
        with:
            fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PUSH_TOKEN }}

      # Build docker image
      - name: Build docker image
        uses: docker/build-push-action@v4
        with:
            context: .
            file: docker/base.Dockerfile
            push: ${{ inputs.push }}
            tags: ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}-base:${{ inputs.tag }}
            build-args: |
                TURBO_TEAM=peersyst
            secrets: |
                turbo_token=${{ secrets.TURBO_TOKEN }}
