name: "Integration"

on:
  pull_request:
    types: [ opened, synchronize ]
  push:
    branches: [ 'main' ]

concurrency:
  # Cancel old runs if there is a new commit in the same branch
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-base:
    uses: ./.github/workflows/integration-packages.yaml
    secrets: inherit
  build-mobile:
    uses: ./.github/workflows/integration-contracts.yaml
    secrets: inherit
