name: test-contracts
on:
    workflow_call:

jobs:
    test-fa-guard-jwt-rs256:
        name: Test FA Guard JWT RS256
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            - name: Run cargo test
              working-directory: ./contracts/fa-guard-jwt-rs256
              run: cargo test

    test-fa-guard-jwt:
        name: Test FA Guard JWT
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            - name: Build mocks
              working-directory: ./contracts/fa-guard-jwt
              run: cargo build --target wasm32-unknown-unknown --release -p jwt-implementation
            - name: Run cargo test
              working-directory: ./contracts/fa-guard-jwt
              run: cargo test

    test-fa-guard:
        name: Test FA Guard
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            - name: Build mocks
              working-directory: ./contracts/fa-guard
              run: cargo build --target wasm32-unknown-unknown --release -p external-guard
            - name: Run cargo test
              working-directory: ./contracts/fa-guard
              run: cargo test
